### ISSUE TITLE
ログイン時の処理について

### ISSUE THREAD

**Issue by Yuta20132** [Yuta20132/musube_node#9]
is_activate=Trueのときのみ,ログインができるようにしたい。
バックエンド側で可能？
フロント側で現在時点ではややこしいため

**Comment by yamma10** [comment]
じゃあアカウントのアクティベートが済んでいないとログインできない=見れないって感じにしますか？

**Comment by Yuta20132** [comment]
掲示板を閲覧できないって認識で大丈夫？

**Comment by yamma10** [comment]
アクティベートが済んでいない→ログインできない→ログインできないと掲示板を閲覧できないって認識でした

**Comment by yamma10** [comment]
あと、is_activeがfalseの場合と、emailが違う場合のエラー文は分けた方がいいですか？

現状、「入力されているemailで、is_activeが真であるレコードを取得する」というクエリを書いているのですが、もしエラー文を分けるとすると、emailでレコードを取得した後にバックエンドでis_activeが真であるかを確認するという処理に変更することになるので

**Comment by Yuta20132** [comment]
アクティベートが済んでいない→ログインできない→ログインできないと掲示板を閲覧できないって認識でした
-> その認識で大丈夫！

あと、is_activeがfalseの場合と、emailが違う場合のエラー文は分けた方がいいですか？
->分けてくれたほうが，フロント側でエラーを出すときにユーザーもわかりやすい

**Comment by Yuta20132** [comment]
ログイン状態の保存はDjangoのときは，Token使ってたけど，node.jsはどのような仕組み使ってる？
@yamma10

**Comment by yamma10** [comment]
ログイン時にクッキーにUUIDを保存して、それをデータベースのlofin_infoというテーブルから参照するようにしていたんですけど、調べた感じ**JWTトークン**というのを使用することで必要な情報全てをトークンとして付与できるみたいなので、**JWTトークン**に変更しようかなと思ってます

**Comment by yamma10** [comment]
is_activeがtrueの時のみログインできるようにして、is_activeがfalseの場合とemailが登録されていない場合のエラー文を分けて、
